export const UPDATE_ORIGINAL = 'UPDATE_ORIGINAL';
export const UPDATE_ADJUSTED = 'UPDATE_ADJUSTED';
export const UPDATE_FLAT = 'UPDATE_FLAT';
export const UPDATE_HEADERS = 'UPDATE_HEADERS';
export const UPDATE_FILENAME = 'UPDATE_FILENAME';